### ISSUE TITLE
can not start

### ISSUE THREAD

**Issue by dumitruc** [danielbayerlein/dashboard#83]
New user.

Fresh Ubuntu 16.04 VM.
Installed Java node, npm , angular.

I've been trying for some time to get this up and running, no luck.

Complain durring npm install:
```
│ ├── babylon@6.18.0 
│ ├── UNMET PEER DEPENDENCY typescript@*
│ └─┬ typescript-eslint-parser@7.0.0 
│   ├── lodash.unescape@4.0.1 
│   └── semver@5.3.0 
├── tinytime@0.2.6 
└─┬ yup@0.23.0 
  ├── case@1.5.4 
  ├── fn-name@1.0.1 
  ├── property-expr@1.3.1 
  ├── synchronous-promise@1.0.18 
  ├── toposort@0.2.12 
  └── type-name@2.0.2 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN typescript-eslint-parser@7.0.0 requires a peer of typescript@* but none was installed.

```

Reproduce:
- Unpack
- Run npm install
- run npm run dev
- open page in browser.

```
 dashboard@1.0.0 dev /opt/GitHub/Dashboard/dashboard-master
> next

> Using external babel configuration
> Location: "/opt/GitHub/Dashboard/dashboard-master/package.json"
> Using "webpack" config function defined in next.config.js.
Failed to load ./.env.


 DONE  Compiled successfully in 3850ms                                  14:14:31

> Ready on http://localhost:3000
> Building page: /


 DONE  Compiled successfully in 10909ms                                 14:15:12

Error: EPERM: operation not permitted, futime
    at Error (native)
    at Object.fs.futimesSync (fs.js:1091:11)
    at TouchSync.futimes (/opt/GitHub/Dashboard/dashboard-master/node_modules/touch/index.js:211:17)
    at TouchSync.onopen (/opt/GitHub/Dashboard/dashboard-master/node_modules/touch/index.js:118:14)
    at TouchSync.open (/opt/GitHub/Dashboard/dashboard-master/node_modules/touch/index.js:176:12)
    at TouchSync.Touch (/opt/GitHub/Dashboard/dashboard-master/node_modules/touch/index.js:82:12)
    at TouchSync (/opt/GitHub/Dashboard/dashboard-master/node_modules/touch/index.js:173:1)
    at Function.module.exports.module.exports.sync.module.exports.touchSync (/opt/GitHub/Dashboard/dashboard-master/node_modules/touch/index.js:20:4)
    at null._onTimeout (/opt/GitHub/Dashboard/dashboard-master/node_modules/next/dist/server/on-demand-entry-handler.js:142:27)
    at Timer.listOnTimeout (timers.js:92:15)

npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! dashboard@1.0.0 dev: `next`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dashboard@1.0.0 dev script 'next'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     next
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/GitHub/Dashboard/dashboard-master/npm-debug.log

```

**Comment by danielbayerlein** [comment]
Hi @dumitruc,

I think the problem is an old version of Node.js. At the moment you use Node.js `v4.2.6`.
Can you please try Node.js >= `v6`?

**Comment by dumitruc** [comment]
Sorry for a late reply _environment issues,_
Updated node.
Solved the problem, not crashing anymore

**Comment by chrishelgert** [comment]
👍
