### ISSUE TITLE
SyntaxError: Unexpected token =>

### ISSUE THREAD

**Issue by kamal2222ahmed** [danielbayerlein/dashboard#84]
~/DEVOPS/TOOLS/DASHBOARDS/dashboard$ sudo npm run dev

> dashboard@1.0.0 dev /Users/a3x52zz/DEVOPS/TOOLS/DASHBOARDS/dashboard
> next

/Users/a3x52zz/DEVOPS/TOOLS/DASHBOARDS/dashboard/next.config.js:4
  webpack: (config) => {
                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadConfig (/Users/a3x52zz/DEVOPS/TOOLS/DASHBOARDS/dashboard/node_modules/next/dist/server/config.js:57:28)
    at getConfig (/Users/a3x52zz/DEVOPS/TOOLS/DASHBOARDS/dashboard/node_modules/next/dist/server/config.js:41:20)
    at Object.<anonymous> (/Users/a3x52zz/DEVOPS/TOOLS/DASHBOARDS/dashboard/node_modules/next/dist/bin/next:95:39)

npm ERR! Darwin 16.7.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! dashboard@1.0.0 dev: `next`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dashboard@1.0.0 dev script 'next'.
npm ERR! This is most likely a problem with the dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     next
npm ERR! You can get their info via:
npm ERR!     npm owner ls dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/a3x52zz/DEVOPS/TOOLS/DASHBOARDS/dashboard/npm-debug.log
~/DEVOPS/TOOLS/DASHBOARDS/dashboard$ /Users/a3x52zz/DEVOPS/TOOLS/DASHBOARDS/dashboard/node_modules/next/node_modules/glob-promise/lib/index.js:6
  return new Promise((resolve, reject) => {
                                       ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/a3x52zz/DEVOPS/TOOLS/DASHBOARDS/dashboard/node_modules/next/dist/server/resolve.js:141:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by danielbayerlein** [comment]
Hi @kamal2222ahmed, I think the problem is an old version of Node.js. At the moment you use Node.js `v0.12.7`. Can you please try Node.js >= `v6`? See #83

**Comment by danielbayerlein** [comment]
@kamal2222ahmed Does it work now?
